sonar.projectKey=henrique-ps_MULISTER_mulister-app
sonar.organization=henrique-ps

sonar.sources=src
sonar.tests=src
sonar.test.inclusions=**/*.spec.ts,**/*.e2e-spec.ts
sonar.javascript.lcov.reportPaths=coverage/lcov.info
sonar.sourceEncoding=UTF-8