name: Backend CI (NestJS)

on:
  push:
    branches: [ "main", "develop" ]
    paths:
      - 'backend/**'
  pull_request:
    branches: [ "main", "develop" ]
    paths:
      - 'backend/**'

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    
    defaults:
      run:
        working-directory: ./backend

    steps:
    - name: Checkout do código
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Configurar Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '24'

    - name: Instalar dependências
      run: pnpm ci

    - name: Rodar Linter
      run: pnpm run lint

    - name: Rodar Testes Unitários e gerar coverage
      run: pnpm run test:cov

    - name: SonarCloud Scan
      uses: SonarSource/sonarcloud-github-action@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      with:
        projectBaseDir: backend